---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: 
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: zookeeper
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name:  zookeeper
        image: {{ .Values.images.zookeeper }}
        imagePullPolicy: Always
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        ports:
        - containerPort: 2181
          protocol: TCP
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: 
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: kafka
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.images.kafka }}
        imagePullPolicy: Always
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        ports:
        - containerPort: 9092
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: kafka
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: kafka
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: 
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: kafka-connector
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-connector
    spec:
      containers:
      - name: kafka-connector
        image: {{ .Values.images.kafka-connector }}
        imagePullPolicy: Always
---
